### ISSUE TITLE
Browser should close even if the TestCleanup method has cleanup errors

### ISSUE THREAD

**Issue by gchirila** [CosminSontu/SpecDrill#24]
Scenario:
1. Override TestCleanup method
public override void TestCleanup()
        {
            //my cleanup method(we use EF to manipulate the DB) 
        }
2. Run the test
Actual Result: 
2. Browser is not closed after the cleanup is done
Expected Result:
2. Browser should close after the cleanup is done

Work around:
Add a try/catch/finally in TestClean up. Ex:
public override void TestCleanup()
        {
            try
            {
                //clean up method
            }
            catch (Exception e)
            {
                Log.Info(e);
            }
            finally
            {
                Browser.Exit();
            }

        }

**Comment by CosminSontu** [comment]
exceptions are caught and logged in SpecDrill's TestBase class. (MsTest variant in this case)

**Comment by CosminSontu** [comment]
c6fc3e2575c538a9e8ea7ccfde908b0c38634fdf
