### ISSUE TITLE
Add possibility to manipulate cookies of the domain

### ISSUE THREAD

**Issue by gchirila** [CosminSontu/SpecDrill#26]
Scenario:
1. Login app
2. Get/Add/Delete session cookies as the webdriver allows it to do: 
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.Options.html

Actual Result: 
Methods are not exposed

Expected Result:
Methods should be exposed

**Comment by CosminSontu** [comment]
Implemented with commit 30be2c7.

IBrowser / Browser classes in SpecDrill now also expose the following methods:

 ```
void AddCookie(Model.Cookie cookie);
 IEnumerable<Model.Cookie> AllCookies { get; }
 void DeleteAllCookies();
 void DeleteCookie(Model.Cookie cookie);
 void GetCookieByName(string name);
 void DeleteCookieByName(string name);
```

Please log further issues if you encounter any.
Thanks!
