### ISSUE TITLE
Expose Browser  Capabilities

### ISSUE THREAD

**Issue by mihaiBoz** [CosminSontu/SpecDrill#30]
Scenario:
It would be nice for Browser capabilities to be exposed.
Actual Result: 

Expected Result:

**Comment by CosminSontu** [comment]
Capabilities were exposed for all situations:
local driver, remote driver, Appium

now all capabilities specified in json file are propagated to targeted driver instance.
There is no validation so the user must specify correct casing for capability names and correct types in specDrillConfig.json

e.g.  below, enableVNC is boolean and platform is string:
//specDrillConfig.json
{
  "webdriver": {
   ...
    "browser": { 
      ...
      "capabilities": {
          "enableVNC":  false,
          "platform": "LINUX"

      }
...
}
...
}
4bdbc50
