### ISSUE TITLE
Remove AcceptInsecureCertificates from BuildInternetExplorerOptions

### ISSUE THREAD

**Issue by gchirila** [CosminSontu/SpecDrill#33]
Scenario:
1. Have IEDriverServer in project nuget references 
2. In specDrillConfig, set the browser name to be ie
3. Run test

Actual Result: 
3. Test doesn't run  and the following error is displayed in output: 
 System.InvalidOperationException: No matching capability sets found.
Unable to match capability set 0: acceptInsecureCerts was 'true', but the IE driver does not allow bypassing insecure (self-signed) SSL certificates (SessionNotCreated)
Please read [https://github.com/SeleniumHQ/selenium/issues/4704]

Expected Result:
3. Test should run

**Comment by CosminSontu** [comment]
Fixed with commit 1c6104775bb4ca6829a4c82fb6489adbf25167ae
