### ISSUE TITLE
Apply navigation on a ListElement<T>

### ISSUE THREAD

**Issue by stasonac** [CosminSontu/SpecDrill#42]
Is there a way we can add navigation to a ListElement<WebControl> ?

Lets say on UI I have a list of cards where a card is a webcontrol, 
And when user clicks on a card a specific webcontrol or module is opened 
I would like to define the list as ListElement<INavigationElement<Module | WebControl>> cards
So clicking on first card for example will navigate to a specific webcontrol( or module) of the page.

**Comment by CosminSontu** [comment]
Now one can target WebContorls with INavigationElement<T>, where T can be either a WebPage or a WebControl.
ae607234024ba09a08408d26c43e4d02193c9ab3
