### ISSUE TITLE
How can I set download folder for chrome in specDrill config json?

### ISSUE THREAD

**Issue by ralluioana** [CosminSontu/SpecDrill#44]
Scenario: I would like to have a certain folder for the downloads in Chrome. Is this possible ?

I tried this but it did not work.
"chrome": {
   "path": "%USERPROFILE%\\.nuget\\packages\\Selenium.WebDriver.ChromeDriver\\116.0.5845.9600\\driver\\win32",
   "arguments": [
      "--ignore-certificate-errors",
      "--download.default_directory=C:\\Downloads\\New folder"
   ]
}

And tried this and did not work.
 "preferences": [ "--download.default_directory=C:\\Downloads\\New folder" ]

**Comment by CosminSontu** [comment]
Applied fix 09cb03d

In specDrillConfig.json you should be able to specify preferences as follows:


```
//...
"drivers": {
  "chrome": {
    "path": "%USERPROFILE%\\.nuget\\packages\\selenium.webdriver.chromedriver\\116.0.5845.9600\\driver\\win32",`
    "arguments": [
      "headless",
      "--disable-extensions",
      "disable-features=VizDisplayCompositor",
      "--incognito",
      "--enable-javascript",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--ignore-certificate-errors"
    ],
    "preferences": {
      "download.default_directory": "%USERPROFILE%\\Downloads",
      "intl.accept_languages": "nl",
      "disable-popup-blocking": true
    }
  },
//...
```

Please try again with latest version (SpecDrill vSpecDrill.1.3.0.1218).

Feel free to provide feedback if this is not working.
Thanks!
